### ISSUE TITLE
Feedback.

### ISSUE THREAD

**Issue by 89gsc** [kokspflanze/alpha-vantage-api#1]
If you intend to release this as a package as you have it might be an idea to improve your documentation as well as listing other required packages you have used like "GuzzleHttp".

**Comment by 89gsc** [comment]
I see composer would include this can't use composer in the intended use case here so I retract my issue, your docs are still light but I will have to do something else can't use composer in this current project I have (out of my hands)

**Comment by kokspflanze** [comment]
@gsc89 the project is still in progress, i work on it when i have a time, i see what i can do in next days =)

**Comment by 89gsc** [comment]
Yeah sorry I was a bit flustered when I first commented as I had been messing around in PHP pulling the JSON direct and still am, I really hate the way they have laid out their keys with spaces in them it's just annoying for some handling I am doing.

**Comment by kokspflanze** [comment]
yeah i understand what you mean, i was thinking to change these keys to smth normal without these spaces, maybe replace with `_` or smth like that.
