### ISSUE TITLE
Currency Converter with PHP and HTML

### ISSUE THREAD

**Issue by Wotan6891** [kokspflanze/alpha-vantage-api#20]
Hello.

I have a code with PHP, HTML and CSS.

It's fine as I like it, but I want it to be calculated automatically without having to put the values. for that reason I want to use the Alpha Advantage API.

but I don't know where to put the API.

can you help me? If so, I immediately pass the code to you.

**Comment by kokspflanze** [comment]
hello, 
i would not recommend to use the api foreach request, better you create 1 request foreach currency and than you do your own calculation.

best ask a freenlancer todo that

**Comment by Wotan6891** [comment]
thanks for the reply sir.
I was interested in learning, I only need that. Greetings,
